### ISSUE TITLE
DerivationSubpath improvements & use

### ISSUE THREAD

**Issue by dr-orlovsky** [BP-WG/descriptor-wallet#36]
- [ ] Implement `Deref`
- [ ] Use for terminal path
- [ ] Use for account path
- [ ] Use in method arguments

**Comment by dr-orlovsky** [comment]
Closed in 8f11ec93f4cfb8925dfa95e175ad721b846b4fd9
